### ISSUE TITLE
assume 128-bit enabled?

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#106]
Currently, we require MonetDB to be compiled with 128-bit support disabled, since NumPy doesn't support 128-bit ints. 

When we compile, install and test MonetDBe-Python with the default OS X monetdb homebrew installation the test suite fails, since the 128-bit mode is enabled by default. Maybe we should just follow the default MonetDB value and raise an error when one tries to access a 128-bit column?

**Comment by njnes** [comment]
Indeed going for a default with 128bit (available but not used by numpy) sounds good.

**Comment by gijzelaerr** [comment]
done!
