### ISSUE TITLE
Make a OSX ARM wheel

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#107]

**Comment by gijzelaerr** [comment]
https://github.com/Homebrew/brew/issues/7857

**Comment by njnes** [comment]
When the build process is clear, we could easily add this too the m1 machine.

**Comment by gijzelaerr** [comment]
numpy and pandas don't have binary wheels for OSX M1 yet, once they are released we should have a look
