### ISSUE TITLE
Use prebuild monetdbe dll for windows from monetdb test builds

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#128]
our CI for windows is quite fragile. It would already help a lot of we could use the prebuild monetdb build results, but these are currently missing the monetdbe.dll.

**Comment by sjoerdmullender** [comment]
The monetdbe.lib and monetdbe.dll have been added to the installer, in time for an Oct2020-SP5 release.
Should also be there for the next nightly.

**Comment by gijzelaerr** [comment]
perfect, thanks!
