### ISSUE TITLE
Queries on INT and BIGINT returning incorrect results in Python?

### ISSUE THREAD

**Issue by wfs-lilly** [MonetDBSolutions/MonetDBe-Python#136]
I'm on version 0.9, Python 3.8, Unix.

I have a table:
```
cur = con.execute("""CREATE TABLE hashes_int2 
(seq_hash_1 INT NOT NULL, 
seq_hash_2 INT NOT NULL,
seq_hash_3 INT NOT NULL,
seq_hash_4 INT NOT NULL
)""")
```

And I fill it from a Pandas dataframe with lots of different int32 values:
![image](https://user-images.githubusercontent.com/57267110/119183720-7a749280-ba42-11eb-9936-eae9dc846e14.png)

But then I get very strange results from queries:
![image](https://user-images.githubusercontent.com/57267110/119184145-05ee2380-ba43-11eb-828b-dace49b595c1.png)

I get the same behavior when my fields are of type BIGINT.

I feel like I must be doing something stupid, but the queries look correct.

**Comment by njnes** [comment]
fix is in the oct branch

**Comment by gijzelaerr** [comment]
What about `Jul2021`? I'm about to publish 0.10 based on `Jul2021`.

**Comment by njnes** [comment]
fix is propagated too jul

**Comment by gijzelaerr** [comment]
perfect, I'll publish the 0.10 binary wheels on Friday then, including this fix.
