### ISSUE TITLE
monetdbe append handles all types (currently no conversion)

### ISSUE THREAD

**Issue by njnes** [MonetDBSolutions/MonetDBe-Python#139]
We could call monetdbe_append on all types (not just int/float)

As of Jul2021 we support all base types. 
Conversion still isn't.

**Comment by gijzelaerr** [comment]
according to Niels this depends on some work Aris is doing (decimal helper function).

**Comment by gijzelaerr** [comment]
i've added boolean and uint, but what other types are supported now and how should they be formatted?

supported numpy kinds:
```
    'b'  boolean
    'i'   signed integer
    'u'   unsigned integer
    'f'   floating-point
```
other:
```
      c complex floating-point
     m timedelta
     M datetime
     O object
     S (byte-)string
     U Unicode
     V void
```

**Comment by njnes** [comment]
string (unicode utf8) datetime  should work

**Comment by gijzelaerr** [comment]
string has been implemented, @aris-koning is having a look if we can get datetime support added also.

**Comment by njnes** [comment]
maybe just documentation? And possibly explain the finer details about decimals.
