### ISSUE TITLE
CREATE VIEW statement

### ISSUE THREAD

**Issue by clbouvier** [MonetDBSolutions/MonetDBe-Python#145]
**Describe the bug**
`CREATE VIEW myview ...` execution raises

> monetdbe.exceptions.DatabaseError: CREATE VIEW: name 'myview' already in use

Is CREATE VIEW statement supported?
Anyway the exception message is unclear.

I am not using the cursor correctly?

**To Reproduce**
```
with monetdbe.connect(autocommit=True) as conn:
    cur = conn.execute("""
CREATE TABLE IF NOT EXISTS mydata(
    sensor VARCHAR(64) NOT NULL,
    dt TIMESTAMP NOT NULL,
    val INTEGER NOT NULL,
    exponent INTEGER NOT NULL,
    CONSTRAINT data_pk PRIMARY KEY(sensor, dt)
    )""")
    cur.execute(
        "CREATE VIEW myview AS SELECT m.sensor, m.dt, m.val * power(10, m.exponent) FROM mydata m")
```

> The error is SQLException:sql.catalog:42S01!CREATE VIEW: name 'myview' already in use
>monetdbe.exceptions.DatabaseError: CREATE VIEW: name 'myview' already in use

**Expected behavior**
If CREATE VIEW is supported, a view is created,
else a 'Statement not supported' error.

**Software versions**
 - OS and version: MacOS 11.4
- Python version: 3.9
 - MonetDBe-Python version: 0.10.1

**Additional context**
CREATE OR REPLACE VIEW myview is silently discarded (none exception is raised)
However an error is raised when  `"SELECT * FROM myview"` is executed:

> monetdbe.exceptions.OperationalError: SELECT: no such table 'myview'

**Comment by gijzelaerr** [comment]
@njnes shouldn't this be detected in the monetdbe engine?

**Comment by njnes** [comment]
problem seems too be that the view is already created during the prepare call.

**Comment by njnes** [comment]
fix is in jul2021

**Comment by clbouvier** [comment]
Hi,

with the same version 0.10.1,
 I hit the kind bug with function ;
I imagine that this bug is more generic than view (when I see the commit in MonetDB).

For instance:

```python
with monetdbe.connect() as conn:
        cur = conn.cursor()
        cur.execute("""
        CREATE FUNCTION only_timestamp(t TIMESTAMP, s VARCHAR(64))
        RETURNS TIMESTAMP
        BEGIN
        RETURN t;
        END;
        """)
```

raises
> monetdbe.exceptions.OperationalError: CREATE FUNCTION: name 'only_timestamp' (timestamp(7), varchar(64)) already in use

Do you want another issue if it not related ?  should I wait the new release ?

**Comment by njnes** [comment]
yes the bug is generic, ie any prepare (and the new monetdbe version does a lot via prepare's) ddl query hits this issue.
