### ISSUE TITLE
INSERT in merge table segfault.

### ISSUE THREAD

**Issue by clbouvier** [MonetDBSolutions/MonetDBe-Python#148]
**Describe the bug**
data insertion in a merge table segfaulted.
data is inserted correctly if not merge table.

**To Reproduce**
```python
merge_table_mysensor = """
CREATE MERGE TABLE mysensor(
sensor VARCHAR(64) NOT NULL,
val INTEGER NOT NULL,
exponent INTEGER NOT NULL,
CONSTRAINT mysensor_pk PRIMARY KEY(sensor)
) PARTITION BY RANGE ON (sensor)
"""

mysensor_ac = """
CREATE TABLE mysensor_ac(
sensor VARCHAR(64) NOT NULL,
val INTEGER NOT NULL,
exponent INTEGER NOT NULL,
CONSTRAINT mysensor_ac_pk PRIMARY KEY(sensor)
)
"""

merge_mysensor_ac = """
ALTER TABLE mysensor ADD TABLE mysensor_ac AS PARTITION FROM 'a' TO 'c'
"""
conn = monetdbe.connect()
cur = conn.execute(merge_table_mysensor)
cur = cur.execute(mysensor_ac)
cur.execute(merge_mysensor_ac)

cur.executescript(
 """INSERT INTO mysensor(sensor, val, exponent)
       VALUES('a', 123, -1);
COMMIT;
""")
```

**Software versions**
 - OS and version: MacOS Big Sur 11.4
- Python version: 3.9
 - MonetDBe-Python version: 0.10.1
 
 with fault handler the stack trace is the following:
 
> Fatal Python error: Segmentation fault

> Current thread 0x0000000103345e00 (most recent call first):
>   File "/Users/cbouvier/prj/dbembedded/lib/python3.9/site-packages/monetdbe/_cffi/internal.py", line 270 in prepare
>   File "/Users/cbouvier/prj/dbembedded/lib/python3.9/site-packages/monetdbe/connection.py", line 316 in prepare
>   File "/Users/cbouvier/prj/dbembedded/lib/python3.9/site-packages/monetdbe/cursors.py", line 123 in _execute_monetdbe
>   File "/Users/cbouvier/prj/dbembedded/lib/python3.9/site-packages/monetdbe/cursors.py", line 142 in execute
>   File "/Users/cbouvier/prj/dbembedded/lib/python3.9/site-packages/monetdbe/cursors.py", line 209 in executescript
>   File "/Users/cbouvier/prj/dbembedded/bug_monetdbe.py", line 85 in <module>

Related to bug #145 with prepare statement?

**Comment by PedroTadim** [comment]
The issue comes from the index generated from the primary key. It is trying to update the index while at the same time it generates the validation for the partition. I think at the moment this should be disabled.

**Comment by clbouvier** [comment]
Ok, thanks.

**Comment by PedroTadim** [comment]
I just pushed the restriction on Jul2021 branch.

**Comment by gijzelaerr** [comment]
This will land in 0.11
