### ISSUE TITLE
Get MonetDBlite test suite working (tests/test_lite/test_pylite00.py)

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#43]
for MonetDBlite these queries are all executed on the same database:
```
        monetdbe.sql('CREATE TABLE pylite00 (i INTEGER)')
        monetdbe.sql('INSERT INTO pylite00 VALUES (1), (2), (3), (4), (5)')
        result = monetdbe.sql('SELECT * FROM pylite00')
```

because how we manage multiple connection with monetdbe, every statement is executed in a new in-memory database.

**Comment by mlkersten** [comment]
No monetdblite compability. remainder moved into separate issue.

**Comment by gijzelaerr** [comment]
Still, there are some lite tests that might be testing some interesting edge cases. I'm going to reopen this issue and rename it.

**Comment by gijzelaerr** [comment]
This has been fixed
