### ISSUE TITLE
#main thread: createExceptionInternal: !ERROR: MALException:sql.start:sabaoth not initialized

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#55]
when using monetdbe the non vital error is printed to console:

#main thread: createExceptionInternal: !ERROR: MALException:sql.start:sabaoth not initialized

**Comment by njnes** [comment]
with which steps did you still see this?

**Comment by gijzelaerr** [comment]
, just checked again, if I run the latest default MonetDBe with my current master branch I see about 45 start:sabaoth not initialized errors when running the test suite

**Comment by gijzelaerr** [comment]
This issue seems to be resolved in the latest default MonetDBe branch
