### ISSUE TITLE
lowlevel.query() sometimes receives empty connection

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#60]

**Comment by njnes** [comment]
seems fixed

**Comment by gijzelaerr** [comment]
I'm still experiencing this issue sporadically.

**Comment by gijzelaerr** [comment]
The issue is not easy to reproduce (yet), but I get it when I run the test suite multiple times. I also saw this error come by once:

```monetdbe.exceptions.DatabaseError: MALException:monetdbe.monetdbe_result_fetch:MonetDBe has not yet started```

**Comment by gijzelaerr** [comment]
This code seems to deterministically reproduce the issue:
```
import monetdbe

q = "create table test(i int)"
m = monetdbe.connect()
c = m.cursor()
c.execute(q)
del m
m = monetdbe.connect()
c = m.cursor()
c.execute(q)
```

**Comment by gijzelaerr** [comment]
I think this issue has been resolved.
