### ISSUE TITLE
Implicite quoting reserved identifiers

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/MonetDBe-Python#61]
**Describe the bug**
The SQLite 3 api includes a helper routine to automatically quote reserved names, such as year.

This means the following query succeeds on SQLite and fails on monetdbe 

**To Reproduce**
```
CREATE TABLE Movies
        (id SERIAL, title TEXT NOT NULL, year INTEGER NOT NULL)
```

**Expected behavior**
the SQL scoping rules should resolve this particular case, or we have to add a helper
at the python side as well. Helper function could be borrowed from sqlite.

**Software versions**
 - OS and version: [e.g. Ubuntu 18.04]
- Python version: [e.g. 3.7]
 - MonetDBe-Python version: [e.g. 0.7]

**Comment by gijzelaerr** [comment]
So you want the python code to rewrite the SQL query? That requires quite some work since we then need to parse the SQL

**Comment by mlkersten** [comment]
No, not now at least, because it has to come from the SQL parser to start with.

**Comment by gijzelaerr** [comment]
if spare time pull this into 0.9

**Comment by gijzelaerr** [comment]
mauybe sue SQLite version in python to do this

**Comment by mlkersten** [comment]
Let's not spent time on this one
