### ISSUE TITLE
Early bailout upon accessing a server database

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/MonetDBe-Python#64]
**Describe the bug**
Nothing precludes the user to access a directory holding a database created with the server option before.  This creates a long blur of error messages. We should detect it is a server-based database (e.g. pinging monetdb(d) and produce a proper error message, or allow for this case with the global database lock. Possibly nullifying the geom types in embedded mode.
 
**To Reproduce**
```
>>> import monetdbe
>>> c = monetdbe.connect('/export/scratch1/mk/dbfarm/demo')
#main thread: load_arg: !ERROR: SQL type 'mbr' is missing
#main thread: mvc_init: !ERROR: Unable to create system tables
#main thread: createExceptionInternal: !ERROR: SQLException:SQLinit:42000!Catalogue initialization failed
#main thread: SQLprelude: !ERROR: Fatal error during initialization: SQLException:SQLinit:42000!Catalogue initialization failed
#main thread: createExceptionInternal: !ERROR: SQLException:SQLinitClient:42000!Catalogue not available
#main thread: createExceptionInternal: !ERROR: SQLException:SQLexitClient:42000!Catalogue not available
SQLException:SQLinitClient:42000!Catalogue not available
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ufs/mk/.virtualenvs/dbfarm-_k_kHpIS/lib/python3.7/site-packages/monetdbe/dbapi2.py", line 48, in connect
    return Connection(*args, **kwargs)
  File "/ufs/mk/.virtualenvs/dbfarm-_k_kHpIS/lib/python3.7/site-packages/monetdbe/connection.py", line 61, in __init__
    raise exceptions.OperationalError(e) from None
monetdbe.exceptions.OperationalError: Catalogue not available
```

**Expected behavior**
ERROR: you attempt to directly access a database managed in server mode only.

**Software versions**
 - OS and version: OSX
- Python version: 3.8
 - MonetDBe-Python version: 0.7.1

**Comment by gijzelaerr** [comment]
Niels is going to improve the error message in oct2020

**Comment by njnes** [comment]
Traceback (most recent call last):
  File "z.py", line 7, in <module>
    con2 = monetdbe.connect(db_path, timeout=0.1)
  File "/home/niels/data/monetdbe/monetdbe/dbapi2.py", line 48, in connect
    return Connection(*args, **kwargs)
  File "/home/niels/data/monetdbe/monetdbe/connection.py", line 58, in __init__
    self.lowlevel: Optional[MonetEmbedded] = MonetEmbedded(dbdir=database)
  File "/home/niels/data/monetdbe/monetdbe/_cffi.py", line 131, in __init__
    self._switch()
  File "/home/niels/data/monetdbe/monetdbe/_cffi.py", line 160, in _switch
    self.set_connection(self.open(self.dbdir))
  File "/home/niels/data/monetdbe/monetdbe/_cffi.py", line 209, in open
    raise exceptions.OperationalError(f"Failed to open database: {error} (code {result_code})")
monetdbe.exceptions.OperationalError: Failed to open database: SQLException:SQLinitClient:42000!Catalogue not available (code -2)

**Comment by njnes** [comment]
Current error is reduced already.
