### ISSUE TITLE
Connect call optional arguments

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/MonetDBe-Python#66]
**Feature request**
Extend the list of properties in the connect() call with
* nr_threads=<integer>  to control the  level of parallelism  (0=all cores used)
* memorylimit=<bigint> to control the memory footprint allowed in :memory: mode in MB
* querytimeout=<int> seconds before a query is forced to terminate
* logging=<location> the file location for the tracer files
* username=<name> used to connect to a remote server
* password=<string> credentials to reach the remote server
* port=<portnr> optional TCP/IP port to listen for connections

**Comment by mlkersten** [comment]
For a web frontend, it would be helpful to set if pagination is allowed and what the page size would be.

**Comment by mlkersten** [comment]
For the memory limit, do we count in bytes? or GB?

**Comment by gijzelaerr** [comment]
implemented on the Python side
