### ISSUE TITLE
Transaction brackets cause problems

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/MonetDBe-Python#70]
**Describe the bug**
See the imdb.py example.
It complaints about a nested transaction, while the autocommit was set to False upon the connection.

python imdb.py 
SQLException:sql.trans:25001!START TRANSACTION: cannot start a transaction within a transaction
Traceback (most recent call last):
  File "imdb.py", line 57, in <module>
    cur.transaction()
  File "/usr/local/lib/python3.7/site-packages/monetdbe/cursor.py", line 427, in transaction
    return self.execute("BEGIN TRANSACTION")

**Software versions**
 - OS and version: [e.g. OSX]
- Python version: [e.g. 3.7]
 - MonetDBe-Python version: [e.g. 0.8]

**Comment by njnes** [comment]
auto commit False means you started a transaction.
ie this is a feature we had/have in the server as 
well.
