### ISSUE TITLE
libcrypto not properly picked up in binary wheel

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#72]
Monetdbe requires libcrypto from openssl. Somewhere the binary wheel construction tools don't pick up this dependency.

This changed, since as far as I know with the monetdbe C code bundled with previous releases didn't have a hard dependency on openssl.

This might be related to the comment in the pep spec:

https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy

"libcrypt.so.1 was retrospectively removed from the whitelist after Fedora 30 was released with libcrypt.so.2 instead."

**Comment by njnes** [comment]
I'm sure this changed because of the authentication code now being used during startup. This is strictly speaking not needed, but given furture plans which may involve users authenticating, we should keep this.

**Comment by gijzelaerr** [comment]
a workaround, for now, could be to disable this so the binary wheel works while we find a solution to this problem?

**Comment by mlkersten** [comment]
I would opt for temporarily disabling it, because the first release should not fall flat on its face due to future requirements

**Comment by njnes** [comment]
I've added a cmake option for this.
-DWITH_CRYPTO=OFF should do the trick now.

**Comment by gijzelaerr** [comment]
ill build and push a new release with this flag disabled in a bit. Are there no other issues that require love for 0.8.1?

**Comment by gijzelaerr** [comment]
0.8.1 pushed to pypi for Linux, OSX build fails.
