### ISSUE TITLE
Avoid debugging and assertions in wheels

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/MonetDBe-Python#74]
**Describe the bug**
Performance analysis indicates that the binary wheels probably are not build with debugging and assertions disables.
This gives a significant performance hit.

**Software versions**
 - OS and version: [e.g. Ubuntu 18.04]
- Python version: [e.g. 3.7]
 - MonetDBe-Python version: [e.g. 0.7]

**Comment by gijzelaerr** [comment]
would adding ` -DCMAKE_BUILD_TYPE=Release` be enough?

**Comment by arjenderijke** [comment]
That should be the solution, but it is not completely implemented in the CMake code of MonetDB. I will add that to my todo list.

**Comment by arjenderijke** [comment]
BTW @mlkersten i would like to have the scripts you use for your performance analysis, to verify the implemented solution.

**Comment by njnes** [comment]
for now use
 -DCMAKE_BUILD_TYPE=Release
-DASSERT=OFF

Last is enabled because we build 'a' non released hg/git checkout. If you build from a clean tar (ie no .hg/.git directory) the -DASSERT should not be needed.

**Comment by gijzelaerr** [comment]
0.8.3 with build type release has been published and uploaded to pypi.
