### ISSUE TITLE
Build monetdb/e as a static library

### ISSUE THREAD

**Issue by yzchang** [MonetDBSolutions/MonetDBe-Python#77]
Can be a nice to have feature.  Doesn't it make more sense for an embedded DBMS?

**Comment by gijzelaerr** [comment]
I don't fully understand, you mean the monetdb part of monetdbe? Isn't it possible to compile that statically? 

If not, then I think this issue suits better in the monetdb repository, since the MonetDBe-Python repo is mostly for the Python side of the project.
