### ISSUE TITLE
Oct2020 monetdb branch build fails

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#85]
On ubuntu 20.04 running:

`$ cmake .. -DCMAKE_INSTALL_PREFIX=/home/gijs/opt/monetdb -DINT128=OFF -DWITH_CRYPTO=OFF -DPY3INTEGRATION=OFF`

in the current monetdb Oct2020 branch gives

```
[  0%] Building C object common/stream/CMakeFiles/stream.dir/stream.c.o
/home/gijs/Work/monetdb/MonetDB.hg/common/stream/stream.c: In function 'my_strerror_r':
/home/gijs/Work/monetdb/MonetDB.hg/common/stream/stream.c:416:9: error: ignoring return value of 'strerror_r', declared with attribute warn_unused_result [-Werror=unused-result]
  416 |  (void) strerror_r(error_nr, buf, buflen);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by njnes** [comment]
seems to be related to the 2 versions of strerror_r one returning int (XSI version) and one return (char*) GNU version. I think in this case we end up on the wrong branch because STRERROR_R_CHAR_P is used but never detected.

**Comment by joerivanruth** [comment]
It's an unused-result warning that gets turned into an error. 
The result is indeed unused. I'll check whether that's a problem.
I see no reason to suppose we're in the wrong branch of the #ifdef, actually I think it's the right branch.

**Comment by gijzelaerr** [comment]
This issue seems to be resolved.
