### ISSUE TITLE
Github actions for OSX 10.15 fails

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#88]
OS X on github actions, still on the oscar branch though.

```
[ 74%] Building C object sql/server/CMakeFiles/sqlserver.dir/rel_semantic.c.o
[ 74%] Building C object sql/server/CMakeFiles/sqlserver.dir/rel_select.c.o
ld: can't map file, errno=22 file '/Library/Frameworks/R.framework' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

full log here
https://pipelines.actions.githubusercontent.com/UmNGzrSz9lwG1p1eq4Z69cWLx9Cy1a9NVo0njjxyokHPafwh5p/_apis/pipelines/1/runs/142/signedlogcontent/11?urlExpires=2020-08-28T10%3A36%3A29.2296870Z&urlSigningMethod=HMACV1&urlSignature=XxOMBO97zOmiJ6n8WCsL4CffuohMuqaFDUXAR2kqUaA%3D

**Comment by njnes** [comment]
http://monetdb.cwi.nl/testweb/web/testgrid.php?serial=76538:d85f57f9c8bb&targets=Cla-Darwin-x86_64&module=sql
ie compiled fine last night.

**Comment by gijzelaerr** [comment]
You don't have permission to access /testweb/web/testgrid.php on this server.

**Comment by gijzelaerr** [comment]
This issue seems to be resolved.
