### ISSUE TITLE
SQLException:monetdbe.monetdbe_append:Cannot append 6 into column 't' when running CFFI test suite

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#93]
this is due to improperly preparing the data structure, but I'm not sure what I'm doing wrong.

**Comment by njnes** [comment]
it seems to pass the float data (from the last column) as first column (ie for the tinyint).

**Comment by njnes** [comment]
its sorted on the column name, but should be aligned with the columns in the table.

**Comment by gijzelaerr** [comment]
This has been solved in https://github.com/MonetDBSolutions/MonetDBe-Python/pull/91
