### ISSUE TITLE
MonetDB release build is linked to debug DLLs (Windows)

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#95]
When build on Windows with a Release target set, monetdb (stream.dll) still links to debug libs, specifically:
```
zlibd1.dll
bz2d.dll
libcurl-d.dll
lzmad.dll
```

Other dependencies like xml2, pcre, crypto and iconv seem to be correctly linked.

**Comment by njnes** [comment]
it seems those Find*cmake files define ZLIB::ZLIB with IMPORTED_CONFIGURATIONS RELEASE/DEBUG. This seems still very new. Not sure how to select the proper imported config (cmake documentation isn't clear on this)
.

**Comment by njnes** [comment]
how did you check for the library dependencies?

**Comment by njnes** [comment]
cmake --build . --target ALL_BUILD --config Release
according too google...

**Comment by gijzelaerr** [comment]
Yes, this solves the issue. Will update the instructions.
